AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: guardrail-cfn-logs
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: central-log-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
