"""GitHub PR comment builder and poster.

Builds inline review comment payloads from scan findings and posts them
via the GitHub REST API using only stdlib (urllib).
"""
from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from typing import Any

from ..core.models import Finding, ResourceEvaluation, ScanResult

log = logging.getLogger(__name__)


def build_pr_comments(results: list[ScanResult]) -> list[dict[str, Any]]:
    """Build a list of GitHub PR review comment payloads from scan results.

    Each FAIL finding becomes one comment dict with keys:
        path, line, body
    """
    comments: list[dict[str, Any]] = []
    for scan in results:
        for resource in scan.resources:
            for finding in resource.findings:
                if finding.status != "FAIL":
                    continue
                comments.append(_comment_payload(scan, resource, finding))
    return comments


def build_summary_comment(results: list[ScanResult]) -> str:
    """Build a Markdown summary comment for the entire PR."""
    total_pass = sum(r.passed_findings for r in results)
    total_fail = sum(r.failed_findings for r in results)
    total = total_pass + total_fail
    score = round((total_pass / max(total, 1)) * 100)

    lines = [
        "## GuardRail Compliance Report",
        "",
        f"**Score:** {score}% | **Passed:** {total_pass} | **Failed:** {total_fail}",
        "",
    ]

    if total_fail > 0:
        lines.append("### Failures")
        lines.append("")
        lines.append("| File | Resource | Rule | Severity | Message |")
        lines.append("|------|----------|------|----------|---------|")
        for scan in results:
            for resource in scan.resources:
                for finding in resource.findings:
                    if finding.status != "FAIL":
                        continue
                    lines.append(
                        f"| `{scan.file_path.name}` "
                        f"| `{resource.resource_type}.{resource.resource_name}` "
                        f"| {finding.rule_id} "
                        f"| {finding.severity} "
                        f"| {finding.message} |"
                    )
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [GuardRail Compliance Engine](https://github.com/varad-more/guardrail-compliance-engine)*")
    return "\n".join(lines)


def post_pr_comment(
    *,
    owner: str,
    repo: str,
    pr_number: int,
    body: str,
    token: str | None = None,
) -> dict[str, Any]:
    """Post a top-level comment on a GitHub PR.

    Uses GITHUB_TOKEN env var if *token* is not provided.
    """
    token = token or os.environ.get("GITHUB_TOKEN", "")
    if not token:
        log.warning("No GITHUB_TOKEN set; skipping PR comment.")
        return {"error": "no token"}

    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments"
    return _github_post(url, {"body": body}, token)


def post_review_comments(
    *,
    owner: str,
    repo: str,
    pr_number: int,
    commit_sha: str,
    comments: list[dict[str, Any]],
    token: str | None = None,
) -> dict[str, Any]:
    """Post inline review comments on a GitHub PR.

    Uses GITHUB_TOKEN env var if *token* is not provided.
    """
    token = token or os.environ.get("GITHUB_TOKEN", "")
    if not token:
        log.warning("No GITHUB_TOKEN set; skipping PR review.")
        return {"error": "no token"}

    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    payload = {
        "commit_id": commit_sha,
        "body": "GuardRail compliance review",
        "event": "COMMENT",
        "comments": comments,
    }
    return _github_post(url, payload, token)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _comment_payload(scan: ScanResult, resource: ResourceEvaluation, finding: Finding) -> dict[str, Any]:
    """Build a single inline comment dict."""
    body_parts = [
        f"**{finding.rule_id}** [{finding.severity}]: {finding.message}",
    ]
    if finding.remediation:
        body_parts.append(f"\n**Remediation:** {finding.remediation}")
    if finding.remediation_snippet:
        body_parts.append(f"\n```hcl\n{finding.remediation_snippet}\n```")

    return {
        "path": str(scan.file_path),
        "line": resource.line_number or 1,
        "body": "\n".join(body_parts),
    }


def _github_post(url: str, payload: dict[str, Any], token: str) -> dict[str, Any]:
    """POST JSON to a GitHub API endpoint."""
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        log.error("GitHub API error %d: %s", exc.code, body)
        return {"error": exc.code, "message": body}
